package com.sunrise.zjbomc.service.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.4
 * Thu Nov 12 14:31:44 CST 2015
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://webService.service.zjbomc.sunrise.com/", name = "BomcUserAuthorityWS")
@XmlSeeAlso({ObjectFactory.class})
public interface BomcUserAuthorityWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryPortalOrganizations", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.QueryPortalOrganizations")
    @ResponseWrapper(localName = "queryPortalOrganizationsResponse", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.QueryPortalOrganizationsResponse")
    @WebMethod
    public com.sunrise.zjbomc.service.webservice.QueryPortalOrganizationsResp queryPortalOrganizations(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sunrise.zjbomc.service.webservice.QueryPortalOrganizationsReq arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updatePortalRole", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.UpdatePortalRole")
    @ResponseWrapper(localName = "updatePortalRoleResponse", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.UpdatePortalRoleResponse")
    @WebMethod
    public com.sunrise.zjbomc.service.webservice.UpdatePortalRoleResp updatePortalRole(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sunrise.zjbomc.service.webservice.UpdatePortalRoleReq arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deletePortalRole", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.DeletePortalRole")
    @ResponseWrapper(localName = "deletePortalRoleResponse", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.DeletePortalRoleResponse")
    @WebMethod
    public com.sunrise.zjbomc.service.webservice.DeletePortalRoleResp deletePortalRole(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sunrise.zjbomc.service.webservice.DeletePortalRoleReq arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updatePortalUserPwd", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.UpdatePortalUserPwd")
    @ResponseWrapper(localName = "updatePortalUserPwdResponse", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.UpdatePortalUserPwdResponse")
    @WebMethod
    public com.sunrise.zjbomc.service.webservice.UpdatePortalUserPwdResp updatePortalUserPwd(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sunrise.zjbomc.service.webservice.UpdatePortalUserPwdReq arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addPortalRole", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.AddPortalRole")
    @ResponseWrapper(localName = "addPortalRoleResponse", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.AddPortalRoleResponse")
    @WebMethod
    public com.sunrise.zjbomc.service.webservice.AddPortalRoleResp addPortalRole(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sunrise.zjbomc.service.webservice.AddPortalRoleReq arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setPortalUserRoles", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.SetPortalUserRoles")
    @ResponseWrapper(localName = "setPortalUserRolesResponse", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.SetPortalUserRolesResponse")
    @WebMethod
    public com.sunrise.zjbomc.service.webservice.SetPortalUserRolesResp setPortalUserRoles(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sunrise.zjbomc.service.webservice.SetPortalUserRolesReq arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updatePortalUser", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.UpdatePortalUser")
    @ResponseWrapper(localName = "updatePortalUserResponse", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.UpdatePortalUserResponse")
    @WebMethod
    public com.sunrise.zjbomc.service.webservice.UpdatePortalUserResp updatePortalUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sunrise.zjbomc.service.webservice.UpdatePortalUserReq arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addPortalUser", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.AddPortalUser")
    @ResponseWrapper(localName = "addPortalUserResponse", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.AddPortalUserResponse")
    @WebMethod
    public com.sunrise.zjbomc.service.webservice.AddPortalUserResp addPortalUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sunrise.zjbomc.service.webservice.AddPortalUserReq arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updatePortalOrganization", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.UpdatePortalOrganization")
    @ResponseWrapper(localName = "updatePortalOrganizationResponse", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.UpdatePortalOrganizationResponse")
    @WebMethod
    public com.sunrise.zjbomc.service.webservice.UpdatePortalOrganizationResp updatePortalOrganization(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sunrise.zjbomc.service.webservice.UpdatePortalOrganizationReq arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryPortalUser", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.QueryPortalUser")
    @ResponseWrapper(localName = "queryPortalUserResponse", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.QueryPortalUserResponse")
    @WebMethod
    public com.sunrise.zjbomc.service.webservice.QueryPortalUserResp queryPortalUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sunrise.zjbomc.service.webservice.QueryPortalUserReq arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deletePortalUser", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.DeletePortalUser")
    @ResponseWrapper(localName = "deletePortalUserResponse", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.DeletePortalUserResponse")
    @WebMethod
    public com.sunrise.zjbomc.service.webservice.DeletePortalUserResp deletePortalUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sunrise.zjbomc.service.webservice.DeletePortalUserReq arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addPortalOrganization", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.AddPortalOrganization")
    @ResponseWrapper(localName = "addPortalOrganizationResponse", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.AddPortalOrganizationResponse")
    @WebMethod
    public com.sunrise.zjbomc.service.webservice.AddPortalOrganizationResp addPortalOrganization(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sunrise.zjbomc.service.webservice.AddPortalOrganizationReq arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryPortalRoles", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.QueryPortalRoles")
    @ResponseWrapper(localName = "queryPortalRolesResponse", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.QueryPortalRolesResponse")
    @WebMethod
    public com.sunrise.zjbomc.service.webservice.QueryPortalRolesResp queryPortalRoles(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sunrise.zjbomc.service.webservice.QueryPortalRolesReq arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deletePortalOrganization", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.DeletePortalOrganization")
    @ResponseWrapper(localName = "deletePortalOrganizationResponse", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.DeletePortalOrganizationResponse")
    @WebMethod
    public com.sunrise.zjbomc.service.webservice.DeletePortalOrganizationResp deletePortalOrganization(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sunrise.zjbomc.service.webservice.DeletePortalOrganizationReq arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryPortalUserRoles", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.QueryPortalUserRoles")
    @ResponseWrapper(localName = "queryPortalUserRolesResponse", targetNamespace = "http://webService.service.zjbomc.sunrise.com/", className = "com.sunrise.zjbomc.service.webservice.QueryPortalUserRolesResponse")
    @WebMethod
    public com.sunrise.zjbomc.service.webservice.QueryPortalUserRolesResp queryPortalUserRoles(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sunrise.zjbomc.service.webservice.QueryPortalUserRolesReq arg0
    );
}
