
/*
 * 
 */

package com.sunrise.zjbomc.service.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.sunrise.zjbomc.service.webservice.BomcUserAuthorityWS;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.1.4
 * Thu Nov 12 14:31:44 CST 2015
 * Generated source version: 2.1.4
 * 
 */


@WebServiceClient(name = "BomcUserAuthorityWSImplService", 
                  wsdlLocation = "http://localhost:8080/bomc/service/bomcUserAuthorityWS?wsdl",
                  targetNamespace = "http://impl.webService.service.zjbomc.sunrise.com/") 
public class BomcUserAuthorityWSImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://impl.webService.service.zjbomc.sunrise.com/", "BomcUserAuthorityWSImplService");
    public final static QName BomcUserAuthorityWSImplPort = new QName("http://impl.webService.service.zjbomc.sunrise.com/", "BomcUserAuthorityWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/bomc/service/bomcUserAuthorityWS?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/bomc/service/bomcUserAuthorityWS?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public BomcUserAuthorityWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BomcUserAuthorityWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BomcUserAuthorityWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns BomcUserAuthorityWS
     */
    @WebEndpoint(name = "BomcUserAuthorityWSImplPort")
    public BomcUserAuthorityWS getBomcUserAuthorityWSImplPort() {
        return super.getPort(BomcUserAuthorityWSImplPort, BomcUserAuthorityWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BomcUserAuthorityWS
     */
    @WebEndpoint(name = "BomcUserAuthorityWSImplPort")
    public BomcUserAuthorityWS getBomcUserAuthorityWSImplPort(WebServiceFeature... features) {
        return super.getPort(BomcUserAuthorityWSImplPort, BomcUserAuthorityWS.class, features);
    }

}
